version: '2'
services:
  mysql-service:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=send08
      - MYSQL_DATABASE=plant_care
    networks:
      - my-tier
    ports:
      - "3306:3306"
networks:
  my-tier:
    driver: bridge
