version: '2'
services:
  plant-care-service:
    build:
      context: ../
      dockerfile: docker/plant-care-service/Dockerfile
      args:
        setupfile: service/target/core-service-0.1.0-SNAPSHOT.jar
    image: plant-care-service:0.1.0-SNAPSHOT
    env_file: plant-care-service/plant-care-service.env
    networks:
      - plantnet
    ports:
      - "8083:8083"
networks:
  plantnet:
    driver: bridge
