cassandra:
  host: localhost
  keyspace: plant_care

security.jwt:
  expTime: 15 # mesure in minutes
  refreshExpTime: 60
  tokenIssuer: plantcare.io
  tokenSigningKey: n5Ewr42JCF6m1qcHF8hk

server:
  port: 8083

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  freemarker:
    template-loader-path: classpath:/templates
  datasource:
    url: jdbc:mysql://localhost/plant_care
    username: root
    password: send08
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    username: stonedfox42@gmail.com
    password: Blackmirror123
    host: smtp.gmail.com
    port: 465
    protocol: smtps





